# title of website
title: Navi

# description of website
description: ssyximmlove's navigation site

# favicon of website
favicon: "https://github.com/ssyximmlove.png?size=40"

# your website url
url: https://navi.supaku.cn

# github profile url
github: "https://github.com/ssyximmlove"

# footer message
footer: © 2021-2021 @ssyximmlove

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 自建网站
      sites:
        - name: 火花小站
          description: 我的博客
          url: https://supaku.cn
        - name: RSSHub
          description: 我的RSSHub
          url: https://rss.supaku.cn
        - name: Bark
          description: 我的Bark服务
          url: https://bark.supaku.cn
        - name: Docker
          description: Portainer.io
          url: https://docker.supaku.cn
        - name: 我的导航站
          description: Navi
          url: https://navi.supaku.cn
    